#! /bin/bash
### BEGIN INIT INFO
# Provides:          sprealtimedata
# Required-Start:    $local_fs $remote_fs $networking
# Required-Stop:     $local_fs $remote_fs $networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts sprealtimedata
# Description:       Starts and stops sprealtimedata
### END INIT INFO
# /etc/init.d/sprealtimedata
#

daemon=/usr/local/bin/uwsgi
pid=/var/run/giraffweb.pid
args="--ini /home/marcus/git/pycewe/giraffe.ini -w wsgi --callable app --enable-threads --pythonpath /home/marcus/git/pycewe"

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        echo "Starting giraffweb!"
        start-stop-daemon --make-pidfile -p $pid --start --background --exec $daemon -- $args
        ;;
    stop)
        echo "Stopping script giraffweb!"
        start-stop-daemon --signal QUIT -p $pid --stop $daemon -- $args
        ;;
    reload | restart)
        echo "Restarting worker threads giraffweb"
        kill -HUP $(cat $pid)
        ;;
    *)
        echo "Usage: /etc/init.d/giraffweb {start|stop|reload}"
        exit 1
    ;;
esac

exit 0
